### ISSUE TITLE
Error rendering -  missing comma

### ISSUE THREAD

**Issue by PaulCristina** [ModelOriented/xai2shiny#1]
Error running xai2shiny function, something about a missing comma?

## Data transformations
suppressMessages(library(tidyverse))
suppressMessages(library(data.table))
## Saving data to disk
suppressMessages(library(feather))
suppressMessages(library(arrow))
suppressMessages(library(here))
## Feature engineering
suppressMessages(library(recipes))
suppressMessages(library(yardstick))
## Machine learning
suppressMessages(library(tidymodels))
suppressMessages(library(themis))
## Explainer
suppressMessages(library(DALEX))

dir <- "/home/paulc/projects_Paul/31_user_journey"
# Load models
lasso_model <- readRDS(paste0(dir, "/R/models/02_glmnet/", "final_model_smote.Rds"))
ranger_model <- readRDS(paste0(dir, "/R/models/03_randomForest/", "final_model_smote.Rds"))

# Read data
path <- paste0(dir, "/R/data/processed/", "data_final.parquet")
df.data <- setDT(read_parquet(path))

# Delete col_to_del
col_to_del <- c("username", "user_id", "start_activity",
                "end_activity", "cohort", "min_to_purchase",
                "token_bonus_ratio", "first_purchase")
df.data[, (col_to_del) := NULL]

# Split the data into training and testing sets
set.seed(2020)
train_test_split <- df.data %>%
  initial_split(prop = 0.8, strata = label_fct)

# Set recipie
recipie_num <- training(train_test_split) %>%
  recipe(label_fct ~. ) %>%   # Fomula
  step_mutate(label_fct = as.factor(label_fct)) %>%
  step_normalize(all_predictors()) %>%
  step_smote(label_fct) %>%
  prep()

# create the final data
df.train <- as.data.frame(juice(recipie_num))
df.test <- as.data.frame(bake(recipie_num, new_data = testing(train_test_split)))

# binary variable for explainer
df.testing_original <- testing(train_test_split)
yTest <- as.integer(ifelse(df.testing_original$label_fct == "yes", 1, 0))

df.test <- df.test %>%
  select(-label_fct)

custom_predict <- function(object, newdata) {pred <- predict(object, newdata, type = "prob")
response <- pred$.pred_yes
return(response)}

lasso_explainer <- DALEX::explain(model = lasso_model,
                                  data = df.test,
                                  y = yTest,
                                  predict_function = custom_predict,
                                  label = "Lasso",
                                  colorize = FALSE)
#> Preparation of a new explainer is initiated
#>   -> model label       :  Lasso 
#>   -> data              :  20514  rows  5  cols 
#>   -> target variable   :  20514  values 
#>   -> predict function  :  custom_predict 
#>   -> predicted values  :  numerical, min =  0.1982451 , mean =  0.35857 , max =  0.9535754  
#>   -> model_info        :  package parsnip , ver. 0.1.3 , task classification (  default  ) 
#>   -> residual function :  difference between y and yhat (  default  )
#>   -> residuals         :  numerical, min =  -0.9535754 , mean =  -0.3346352 , max =  0.8017549  
#>   A new explainer has been created!

ranger_explainer <- DALEX::explain(model = ranger_model,
                                   data = df.test,
                                   y = yTest,
                                   predict_function = custom_predict,
                                   label = "Random Forest",
                                   colorize = FALSE)
#> Preparation of a new explainer is initiated
#>   -> model label       :  Random Forest 
#>   -> data              :  20514  rows  5  cols 
#>   -> target variable   :  20514  values 
#>   -> predict function  :  custom_predict 
#>   -> predicted values  :  numerical, min =  0.2152264 , mean =  0.3666207 , max =  0.9012534  
#>   -> model_info        :  package parsnip , ver. 0.1.3 , task classification (  default  ) 
#>   -> residual function :  difference between y and yhat (  default  )
#>   -> residuals         :  numerical, min =  -0.9012534 , mean =  -0.3426858 , max =  0.7847736  
#>   A new explainer has been created!
library(xai2shiny)
xai2shiny(lasso_explainer, ranger_explainer)
#> Loading required package: shiny
#> Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
#>   /tmp/RtmpdRkELf/xai2shiny/app.R:11:1: unexpected ','
#> 10: library(parsnip)
#> 11: ,
#>     ^
#> Possible missing comma at:
#> 30:                                                                                     if(!is.null(header)) tags$li(class="header",header),
#>                                                                                                              ^
#> Possible extra comma at:
#> 127:                                column(width = 3, uiOutput("pdpvariable"),),
#>                                                                              ^
#> Possible missing comma at:
#> 153:      nulls <- sapply(obs, function(x) length(x) == 0)
#>                                            ^
#> Error in sourceUTF8(fullpath, envir = new.env(parent = sharedEnv)): Error sourcing /tmp/RtmpdRkELf/xai2shiny/app.R
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: CentOS Linux 7 (Core)
#> 
#> Matrix products: default
#> BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#>  [1] shiny_1.5.0           xai2shiny_0.1.0       DALEX_2.0            
#>  [4] themis_0.1.2          workflows_0.2.0       tune_0.1.1           
#>  [7] rsample_0.0.8         parsnip_0.1.3         modeldata_0.0.2      
#> [10] infer_0.5.3           dials_0.0.9           scales_1.1.1         
#> [13] broom_0.7.0           tidymodels_0.1.1.9000 yardstick_0.0.7      
#> [16] recipes_0.1.13        here_0.1              arrow_1.0.0.20200728 
#> [19] feather_0.3.5         data.table_1.12.8     forcats_0.5.0        
#> [22] stringr_1.4.0         dplyr_1.0.2           purrr_0.3.4          
#> [25] readr_1.4.0           tidyr_1.1.2           tibble_3.0.4         
#> [28] ggplot2_3.3.2         tidyverse_1.3.0      
#> 
#> loaded via a namespace (and not attached):
#>   [1] readxl_1.3.1          mlr_2.17.1            backports_1.1.10     
#>   [4] fastmatch_1.1-0       plyr_1.8.6            shinydashboard_0.7.1 
#>   [7] splines_4.0.2         listenv_0.8.0         digest_0.6.26        
#>  [10] foreach_1.5.0         htmltools_0.5.0       fansi_0.4.1          
#>  [13] magrittr_1.5          checkmate_2.0.0       BBmisc_1.11          
#>  [16] unbalanced_2.0        doParallel_1.0.15     globals_0.13.0       
#>  [19] modelr_0.1.8          gower_0.2.2           colorspace_1.4-1     
#>  [22] blob_1.2.1            rvest_0.3.5           haven_2.3.1          
#>  [25] xfun_0.17             crayon_1.3.4          jsonlite_1.7.1       
#>  [28] survival_3.1-12       iterators_1.0.12      glue_1.4.2           
#>  [31] gtable_0.3.0          ipred_0.9-9           shape_1.4.4          
#>  [34] DBI_1.1.0             Rcpp_1.0.5            xtable_1.8-4         
#>  [37] GPfit_1.0-8           bit_1.1-15.2          lava_1.6.8           
#>  [40] prodlim_2019.11.13    glmnet_4.0-2          httr_1.4.1           
#>  [43] sourcetools_0.1.7     FNN_1.1.3             ellipsis_0.3.1       
#>  [46] pkgconfig_2.0.3       ParamHelpers_1.14     nnet_7.3-14          
#>  [49] dbplyr_1.4.4          tidyselect_1.1.0      rlang_0.4.8          
#>  [52] DiceDesign_1.8-1      later_1.1.0.1         munsell_0.5.0        
#>  [55] cellranger_1.1.0      tools_4.0.2           cli_2.1.0            
#>  [58] generics_0.0.2        ranger_0.12.1         evaluate_0.14        
#>  [61] fastmap_1.0.1         yaml_2.2.1            knitr_1.30           
#>  [64] bit64_0.9-7           fs_1.4.2              shinycssloaders_1.0.0
#>  [67] RANN_2.6.1            future_1.19.1         whisker_0.4          
#>  [70] mime_0.9              xml2_1.3.2            compiler_4.0.2       
#>  [73] rstudioapi_0.11       reprex_0.3.0          lhs_1.0.2            
#>  [76] stringi_1.5.3         highr_0.8             lattice_0.20-41      
#>  [79] Matrix_1.2-18         shinyjs_2.0.0         vctrs_0.3.4          
#>  [82] pillar_1.4.6          lifecycle_0.2.0       furrr_0.1.0          
#>  [85] httpuv_1.5.4          R6_2.4.1              promises_1.1.1       
#>  [88] renv_0.12.0-12        codetools_0.2-16      MASS_7.3-51.6        
#>  [91] assertthat_0.2.1      rprojroot_1.3-2       shinyWidgets_0.5.4   
#>  [94] ROSE_0.0-3            withr_2.3.0           parallel_4.0.2       
#>  [97] hms_0.5.3             grid_4.0.2            rpart_4.1-15         
#> [100] timeDate_3043.102     class_7.3-17          rmarkdown_2.3        
#> [103] parallelMap_1.5.0     pROC_1.16.2           lubridate_1.7.9
Created on 2020-10-22 by the reprex package (v0.3.0)

**Comment by perevales** [comment]
Same problem with h2o models ("missing comma"):

Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  /private/var/folders/kl/lgspkl39679_svg1dg6bsnmh0000gn/T/RtmpQ7hL6L/xai2shiny/app.R:10:1: inesperado ','
9: library(h2o)
10: ,
    ^
Possible missing comma at:
27:                                                                                     if(!is.null(header)) tags$li(class="header",header),
                                                                                                             ^
Possible extra comma at:
124:                                column(width = 3, uiOutput("pdpvariable"),),
                                                                             ^
Possible missing comma at:
155:      nulls <- sapply(obs, function(x) length(x) == 0)
                                           ^
Error in sourceUTF8(fullpath, envir = new.env(parent = sharedEnv)) : 
  Error sourcing /private/var/folders/kl/lgspkl39679_svg1dg6bsnmh0000gn/T/RtmpQ7hL6L/xai2shiny/app.R

**Comment by laresbernardo** [comment]
Hi! I think I have the same issue running `h2o` underneath as well. 

Reproducible example:
```
library(xai2shiny) # devtools::install_github("ModelOriented/xai2shiny")
library(lares) # devtools::install_github("laresbernardo/lares")
ignore <- c("PassengerId","Ticket","Cabin")
model <- h2o_automl(dft, Survived, ignore = ignore)
explainer <- dalex_explainer(model$datasets$test, model = model$model, y = "Survived", ignore = ignore)
xai2shiny(explainer)
```

This is the error output:
```
Loading required package: shiny
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  /private/var/folders/3w/x0bjsdv52v3b3kjbw87y3wfw0000gn/T/RtmpvdOPU6/xai2shiny/app.R:9:15: unexpected symbol
8: 
9: library(Model of
                 ^
Possible missing comma at:
9:library(Model of class: H2OBinomialModel package unrecognized)
                ^
Possible missing comma at:
9:library(Model of class: H2OBinomialModel package unrecognized)
                   ^
Possible missing comma at:
9:library(Model of class: H2OBinomialModel package unrecognized)
                                           ^
Possible missing comma at:
9:library(Model of class: H2OBinomialModel package unrecognized)
                                                   ^
Possible missing comma at:
26:                                                                                     if(!is.null(header)) tags$li(class="header",header),
                                                                                                             ^
Possible extra comma at:
123:                                column(width = 3, uiOutput("pdpvariable"),),
                                                                             ^
Possible missing comma at:
155:      nulls <- sapply(obs, function(x) length(x) == 0)
                                           ^
Error in sourceUTF8(fullpath, envir = new.env(parent = sharedEnv)) : 
  Error sourcing /private/var/folders/3w/x0bjsdv52v3b3kjbw87y3wfw0000gn/T/RtmpvdOPU6/xai2shiny/app.R
```

**Comment by arydelek** [comment]
Hi! Thank you for your feedback @laresbernardo, @perevales, and @PaulCristina!

### h2o problems:
There is a problem when using h2o because the shiny app.R file takes the model's package from it's `model_info` parameter. 
In order to use h2o with xai2shiny, you need to set the parameter manually. 
There also appears to be an error with variables containing only one unique value, such as the `train_test` variable. I will look into that. For now, the fix is to simply select the variables manually.
Here is the example presented by @laresbernardo fixed.
```
library(xai2shiny) # devtools::install_github("ModelOriented/xai2shiny")
library(lares) # devtools::install_github("laresbernardo/lares")
ignore <- c("PassengerId","Ticket","Cabin")
model <- h2o_automl(dft, Survived, ignore = ignore)
explainer <- dalex_explainer(model$datasets$test, model = model$model, y = "Survived", ignore = ignore)
# Change the model_info$package parameter to the package you want to use
explainer$model_info$package <- "h2o"
# Select the variables manually
xai2shiny(explainer, directory = "xai2shiny_issues", run = TRUE, 
          selected_variables = c("PClass","Sex","Age","SibSp", "Parch", "Fare", "Embarked", "predict", "FALSE.", "TRUE."))
```

### @PaulCristina example:
As for this example, I wasn't able to replicate it. The issue could be similar to h2o.
If you could check your explainers package parameter by:
```
lasso_explainer$model_info$package
ranger_explainer$model_info$package
```
And if it's wrong, set it manually to the correct value, for example:
```
ranger_explainer$model_info$package <- "ranger"
```
In case this does not solve the issue, you could try to create the application file and send me it's content so I can review it thoroughly. To do so create a new directory in your working directory and specify it in the 'directory' parameter, like so:

```
xai2shiny(lasso_explainer, ranger_explainer, directory = "new_directory")
```
Now there will be a subdirectory created named "xai2shiny" containing "app.R" and your models. Please insert "app.R" content in here, so I can review it.

**Comment by laresbernardo** [comment]
Thanks for your reply and suggestions @Adamoso 
I've included these steps automatically into the new `h2o_explainer` function: exclude variables with no variance and define `model_info$package` by default to `h2o`. So now we can run the previous example with no issue without running these steps manually or selecting variables. 
Note that I've changed the `dalex_explainer()` to `h2o_explainer()` as it fits best!

**Comment by PaulCristina** [comment]
Hi @Adamoso , unfortunately it still does not work, the classes looks fine. Changed my data to Telco dataset for reproducibility and added the "app.R" file.
[app.zip](https://github.com/ModelOriented/xai2shiny/files/5435014/app.zip)

 
``` r
# Load libraries
suppressMessages(library(tidyverse))
suppressMessages(library(data.table))
#> Warning: package 'data.table' was built under R version 4.0.3
## Saving data to disk
suppressMessages(library(feather))
suppressMessages(library(arrow))
suppressMessages(library(here))
## Feature engineering
suppressMessages(library(recipes))
suppressMessages(library(yardstick))
## Machine learning
suppressMessages(library(tidymodels))
suppressMessages(library(themis))
## Explainer
suppressMessages(library(DALEX))


# Read data
df.data <- setDT(read.csv("https://raw.githubusercontent.com/treselle-systems/customer_churn_analysis/master/WA_Fn-UseC_-Telco-Customer-Churn.csv"))
df.data[, Churn := tolower(Churn)]
glimpse(df.data)
#> Rows: 7,043
#> Columns: 21
#> $ customerID       <chr> "7590-VHVEG", "5575-GNVDE", "3668-QPYBK", "7795-CFOC…
#> $ gender           <chr> "Female", "Male", "Male", "Male", "Female", "Female"…
#> $ SeniorCitizen    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
#> $ Partner          <chr> "Yes", "No", "No", "No", "No", "No", "No", "No", "Ye…
#> $ Dependents       <chr> "No", "No", "No", "No", "No", "No", "Yes", "No", "No…
#> $ tenure           <int> 1, 34, 2, 45, 2, 8, 22, 10, 28, 62, 13, 16, 58, 49, …
#> $ PhoneService     <chr> "No", "Yes", "Yes", "No", "Yes", "Yes", "Yes", "No",…
#> $ MultipleLines    <chr> "No phone service", "No", "No", "No phone service", …
#> $ InternetService  <chr> "DSL", "DSL", "DSL", "DSL", "Fiber optic", "Fiber op…
#> $ OnlineSecurity   <chr> "No", "Yes", "Yes", "Yes", "No", "No", "No", "Yes", …
#> $ OnlineBackup     <chr> "Yes", "No", "Yes", "No", "No", "No", "Yes", "No", "…
#> $ DeviceProtection <chr> "No", "Yes", "No", "Yes", "No", "Yes", "No", "No", "…
#> $ TechSupport      <chr> "No", "No", "No", "Yes", "No", "No", "No", "No", "Ye…
#> $ StreamingTV      <chr> "No", "No", "No", "No", "No", "Yes", "Yes", "No", "Y…
#> $ StreamingMovies  <chr> "No", "No", "No", "No", "No", "Yes", "No", "No", "Ye…
#> $ Contract         <chr> "Month-to-month", "One year", "Month-to-month", "One…
#> $ PaperlessBilling <chr> "Yes", "No", "Yes", "No", "Yes", "Yes", "Yes", "No",…
#> $ PaymentMethod    <chr> "Electronic check", "Mailed check", "Mailed check", …
#> $ MonthlyCharges   <dbl> 29.85, 56.95, 53.85, 42.30, 70.70, 99.65, 89.10, 29.…
#> $ TotalCharges     <dbl> 29.85, 1889.50, 108.15, 1840.75, 151.65, 820.50, 194…
#> $ Churn            <chr> "no", "no", "yes", "no", "yes", "yes", "no", "no", "…
df.data <- df.data %>% plyr::rename(c("Churn" = "label_fct")) %>% drop_na()
new_dir <- "/home/paulc/projects_Paul/31_user_journey/R/xai2shiny"

# Split the data into training and testing sets
set.seed(2020)
train_test_split <- df.data %>%
  initial_split(prop = 0.8, strata = label_fct)

# Set recipe
recipie_num <- training(train_test_split) %>%
  recipe(label_fct ~. ) %>%   # Fomula
  step_rm(customerID) %>%
  step_mutate(label_fct = as.factor(label_fct)) %>%
  step_dummy(all_nominal(), -label_fct) %>%
  step_normalize(all_predictors()) %>%
  prep()

# create CV object from training data
set.seed(2020)
data_folds <- recipes::bake(
  recipie_num,
  new_data = training(train_test_split)
) %>%
  rsample::vfold_cv(v = 10,
                    # repeats = 2,
                    strata = label_fct)
data_folds
#> #  10-fold cross-validation using stratification 
#> # A tibble: 10 x 2
#>    splits             id    
#>    <list>             <chr> 
#>  1 <split [5.1K/564]> Fold01
#>  2 <split [5.1K/563]> Fold02
#>  3 <split [5.1K/563]> Fold03
#>  4 <split [5.1K/563]> Fold04
#>  5 <split [5.1K/563]> Fold05
#>  6 <split [5.1K/563]> Fold06
#>  7 <split [5.1K/562]> Fold07
#>  8 <split [5.1K/562]> Fold08
#>  9 <split [5.1K/562]> Fold09
#> 10 <split [5.1K/562]> Fold10


# create the final data
df.train <- as.data.frame(juice(recipie_num))
df.test <- as.data.frame(bake(recipie_num, new_data = testing(train_test_split)))

# binary variable for explainer
df.testing_original <- testing(train_test_split)
yTest <- as.integer(ifelse(df.testing_original$label_fct == "yes", 1, 0))

### lasso
model_lasso <- logistic_reg(penalty = tune(),
                      mixture = 1) %>%
  set_engine("glmnet") %>%
  set_mode("classification")


tune_workflow_lasso <- workflow() %>%
  # add the recipe
  add_formula(label_fct ~ .) %>%
  # add the model
  add_model(model_lasso)

set.seed(2020)
params <- grid_max_entropy(penalty(),
                           size = 5)

model_grid_lasso <- tune_grid(
  tune_workflow_lasso,
  resamples = data_folds,
  grid      = params,
  metrics   = yardstick::metric_set(roc_auc, mcc),
  control   = control_grid(verbose = TRUE)
)
#> i Fold01: formula
#> ✓ Fold01: formula
#> i Fold01: model 1/1
#> ✓ Fold01: model 1/1
#> i Fold01: model 1/1
#> ✓ Fold01: model 1/1
#> i Fold02: formula
#> ✓ Fold02: formula
#> i Fold02: model 1/1
#> ✓ Fold02: model 1/1
#> i Fold02: model 1/1
#> ✓ Fold02: model 1/1
#> i Fold03: formula
#> ✓ Fold03: formula
#> i Fold03: model 1/1
#> ✓ Fold03: model 1/1
#> i Fold03: model 1/1
#> ✓ Fold03: model 1/1
#> i Fold04: formula
#> ✓ Fold04: formula
#> i Fold04: model 1/1
#> ✓ Fold04: model 1/1
#> i Fold04: model 1/1
#> ✓ Fold04: model 1/1
#> i Fold05: formula
#> ✓ Fold05: formula
#> i Fold05: model 1/1
#> ✓ Fold05: model 1/1
#> i Fold05: model 1/1
#> ✓ Fold05: model 1/1
#> i Fold06: formula
#> ✓ Fold06: formula
#> i Fold06: model 1/1
#> ✓ Fold06: model 1/1
#> i Fold06: model 1/1
#> ✓ Fold06: model 1/1
#> i Fold07: formula
#> ✓ Fold07: formula
#> i Fold07: model 1/1
#> ✓ Fold07: model 1/1
#> i Fold07: model 1/1
#> ✓ Fold07: model 1/1
#> i Fold08: formula
#> ✓ Fold08: formula
#> i Fold08: model 1/1
#> ✓ Fold08: model 1/1
#> i Fold08: model 1/1
#> ✓ Fold08: model 1/1
#> i Fold09: formula
#> ✓ Fold09: formula
#> i Fold09: model 1/1
#> ✓ Fold09: model 1/1
#> i Fold09: model 1/1
#> ✓ Fold09: model 1/1
#> i Fold10: formula
#> ✓ Fold10: formula
#> i Fold10: model 1/1
#> ✓ Fold10: model 1/1
#> i Fold10: model 1/1
#> ✓ Fold10: model 1/1

best_parameters <- model_grid_lasso %>%
  select_best("roc_auc")


final_model_lasso <-
  model_lasso %>%
  finalize_model(best_parameters) %>%
  fit(label_fct ~ ., data = df.train)

### Ranger
model_ranger <- rand_forest(mtry = tune(),
                     trees = tune(),
                     min_n = tune()) %>%
  set_engine("ranger", importance = "impurity") %>%
  set_mode("classification")


tune_workflow_ranger <- workflow() %>%
  # add the recipe
  add_formula(label_fct ~ .) %>%
  # add the model
  add_model(model_ranger)

model_grid_ranger <- tune_grid(
  tune_workflow_ranger,
  resamples = data_folds,
  grid      = 2,
  metrics   = metric_set(roc_auc, mcc),
  control   = control_grid(verbose = TRUE)
)
#> i Creating pre-processing data to finalize unknown parameter: mtry
#> i Fold01: formula
#> ✓ Fold01: formula
#> i Fold01: model 1/2
#> ✓ Fold01: model 1/2
#> i Fold01: model 1/2
#> ✓ Fold01: model 1/2
#> i Fold01: model 2/2
#> ✓ Fold01: model 2/2
#> i Fold01: model 2/2
#> ✓ Fold01: model 2/2
#> i Fold02: formula
#> ✓ Fold02: formula
#> i Fold02: model 1/2
#> ✓ Fold02: model 1/2
#> i Fold02: model 1/2
#> ✓ Fold02: model 1/2
#> i Fold02: model 2/2
#> ✓ Fold02: model 2/2
#> i Fold02: model 2/2
#> ✓ Fold02: model 2/2
#> i Fold03: formula
#> ✓ Fold03: formula
#> i Fold03: model 1/2
#> ✓ Fold03: model 1/2
#> i Fold03: model 1/2
#> ✓ Fold03: model 1/2
#> i Fold03: model 2/2
#> ✓ Fold03: model 2/2
#> i Fold03: model 2/2
#> ✓ Fold03: model 2/2
#> i Fold04: formula
#> ✓ Fold04: formula
#> i Fold04: model 1/2
#> ✓ Fold04: model 1/2
#> i Fold04: model 1/2
#> ✓ Fold04: model 1/2
#> i Fold04: model 2/2
#> ✓ Fold04: model 2/2
#> i Fold04: model 2/2
#> ✓ Fold04: model 2/2
#> i Fold05: formula
#> ✓ Fold05: formula
#> i Fold05: model 1/2
#> ✓ Fold05: model 1/2
#> i Fold05: model 1/2
#> ✓ Fold05: model 1/2
#> i Fold05: model 2/2
#> ✓ Fold05: model 2/2
#> i Fold05: model 2/2
#> ✓ Fold05: model 2/2
#> i Fold06: formula
#> ✓ Fold06: formula
#> i Fold06: model 1/2
#> ✓ Fold06: model 1/2
#> i Fold06: model 1/2
#> ✓ Fold06: model 1/2
#> i Fold06: model 2/2
#> ✓ Fold06: model 2/2
#> i Fold06: model 2/2
#> ✓ Fold06: model 2/2
#> i Fold07: formula
#> ✓ Fold07: formula
#> i Fold07: model 1/2
#> ✓ Fold07: model 1/2
#> i Fold07: model 1/2
#> ✓ Fold07: model 1/2
#> i Fold07: model 2/2
#> ✓ Fold07: model 2/2
#> i Fold07: model 2/2
#> ✓ Fold07: model 2/2
#> i Fold08: formula
#> ✓ Fold08: formula
#> i Fold08: model 1/2
#> ✓ Fold08: model 1/2
#> i Fold08: model 1/2
#> ✓ Fold08: model 1/2
#> i Fold08: model 2/2
#> ✓ Fold08: model 2/2
#> i Fold08: model 2/2
#> ✓ Fold08: model 2/2
#> i Fold09: formula
#> ✓ Fold09: formula
#> i Fold09: model 1/2
#> ✓ Fold09: model 1/2
#> i Fold09: model 1/2
#> ✓ Fold09: model 1/2
#> i Fold09: model 2/2
#> ✓ Fold09: model 2/2
#> i Fold09: model 2/2
#> ✓ Fold09: model 2/2
#> i Fold10: formula
#> ✓ Fold10: formula
#> i Fold10: model 1/2
#> ✓ Fold10: model 1/2
#> i Fold10: model 1/2
#> ✓ Fold10: model 1/2
#> i Fold10: model 2/2
#> ✓ Fold10: model 2/2
#> i Fold10: model 2/2
#> ✓ Fold10: model 2/2


best_parameters <- model_grid_ranger %>%
  select_best("roc_auc")
best_parameters
#> # A tibble: 1 x 4
#>    mtry trees min_n .config
#>   <int> <int> <int> <chr>  
#> 1     6   213    10 Model2

final_model_ranger <-
  model_ranger %>%
  finalize_model(best_parameters) %>%
  fit(label_fct ~ ., data = df.train)

### Explainers

df.test <- df.test %>%
  select(-label_fct)


custom_predict <- function(object, newdata) {pred <- predict(object, newdata, type = "prob")
response <- pred$.pred_yes
return(response)}


explainer_lasso <- DALEX::explain(model = final_model_lasso,
                            data = df.test,
                            y = yTest,
                            predict_function = custom_predict,
                            label = "lasso",
                            colorize = FALSE)
#> Preparation of a new explainer is initiated
#>   -> model label       :  lasso 
#>   -> data              :  1405  rows  30  cols 
#>   -> target variable   :  1405  values 
#>   -> predict function  :  custom_predict 
#>   -> predicted values  :  numerical, min =  0.001139992 , mean =  0.2707309 , max =  0.8349668  
#>   -> model_info        :  package parsnip , ver. 0.1.3 , task classification (  default  ) 
#>   -> residual function :  difference between y and yhat (  default  )
#>   -> residuals         :  numerical, min =  -0.815669 , mean =  -0.005250503 , max =  0.9973887  
#>   A new explainer has been created!

explainer_ranger <- DALEX::explain(model = final_model_ranger,
                                  data = df.test,
                                  y = yTest,
                                  predict_function = custom_predict,
                                  label = "ranger",
                                  colorize = FALSE)
#> Preparation of a new explainer is initiated
#>   -> model label       :  ranger 
#>   -> data              :  1405  rows  30  cols 
#>   -> target variable   :  1405  values 
#>   -> predict function  :  custom_predict 
#>   -> predicted values  :  numerical, min =  0 , mean =  0.2740226 , max =  0.9525119  
#>   -> model_info        :  package parsnip , ver. 0.1.3 , task classification (  default  ) 
#>   -> residual function :  difference between y and yhat (  default  )
#>   -> residuals         :  numerical, min =  -0.9397243 , mean =  -0.008542143 , max =  0.9949992  
#>   A new explainer has been created!

explainer_lasso$model_info$package
#>   wrapper   package 
#> "parsnip"  "glmnet"
explainer_ranger$model_info$package
#>   wrapper   package 
#> "parsnip"  "ranger"

library(xai2shiny)
xai2shiny(explainer_lasso, explainer_ranger, directory = new_dir)
#> Loading required package: shiny
#> Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
#>   /home/paulc/projects_Paul/31_user_journey/R/xai2shiny/xai2shiny/app.R:11:1: unexpected ','
#> 10: library(parsnip)
#> 11: ,
#>     ^
#> Possible missing comma at:
#> 30:                                                                                     if(!is.null(header)) tags$li(class="header",header),
#>                                                                                                              ^
#> Possible extra comma at:
#> 127:                                column(width = 3, uiOutput("pdpvariable"),),
#>                                                                              ^
#> Possible missing comma at:
#> 178:      nulls <- sapply(obs, function(x) length(x) == 0)
#>                                            ^
#> Error in sourceUTF8(fullpath, envir = new.env(parent = sharedEnv)): Error sourcing /home/paulc/projects_Paul/31_user_journey/R/xai2shiny/xai2shiny/app.R
```

<sup>Created on 2020-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by arydelek** [comment]
@PaulCristina thank you for supplying the example! The problem appears to be that model_info contains both the wrapper: `parsnip` and the model itself, so the package adds an unnecessary comma. I will fix that in the next pull request. For now, just use:
```
explainer_lasso$model_info$package <- "glmnet"
explainer_ranger$model_info$package <- "ranger"

library(xai2shiny)
xai2shiny(explainer_lasso, explainer_ranger)
```

**Comment by arydelek** [comment]
The latest commit fixes all the above-mentioned issues. The package now reads all libraries correctly and ignores variables without variance. 

Thank you for reporting the issues!
